version: 2
updates:
  # Production dependencies - MAJOR UPDATES ONLY
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    rebase-strategy: auto
    labels: ["dependencies", "production", "major-update"]
    commit-message:
      prefix: "deps(prod)"
    # Only include production dependencies (require section)
    allow:
      - dependency-type: "direct:production"
    # Ignore minor and patch updates for production dependencies
    ignore:
      - dependency-name: "guzzlehttp/guzzle"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
      - dependency-name: "league/oauth2-client"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]

  # Dev dependencies - ALL UPDATES
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    rebase-strategy: auto
    labels: ["dependencies", "dev-only"]
    commit-message:
      prefix: "deps(dev)"
    # Only include dev dependencies (require-dev section)
    allow:
      - dependency-type: "direct:development"
    groups:
      dev-dependencies:
        patterns:
          - "*"

  # GitHub Actions - ALL UPDATES  
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    labels: ["ci", "dependencies"]
    commit-message:
      prefix: "ci"
    groups:
      github-actions:
        patterns:
          - "*"
