name: Release Changelog
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate release notes for this tag and prepend to CHANGELOG.md
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.release.toml
          args: --tag "${{ github.ref_name }}" --prepend CHANGELOG.md
        env:
          OUTPUT: CHANGELOG.md

      - name: Commit and push CHANGELOG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "chore: update changelog for $GITHUB_REF_NAME" || echo "No changes to commit"
          git push
